
(function(d){function B(a,b,c){"addEventListener"in d?a.addEventListener(b,c,!1):"attachEvent"in d&&a.attachEvent("on"+b,c)}function V(a,b,c){"removeEventListener"in d?a.removeEventListener(b,c,!1):"detachEvent"in d&&a.detachEvent("on"+b,c)}function e(a){I&&"object"===typeof d.console}function s(a){"object"===typeof d.console}function sa(){var a=W.substr(X).split(":");w=a[0];J=void 0!==a[1]?Number(a[1]):J;C=void 0!==a[2]?"true"===a[2]?!0:
!1:C;I=void 0!==a[3]?"true"===a[3]?!0:!1:I;r=void 0!==a[4]?Number(a[4]):r;m=void 0!==a[6]?"true"===a[6]?!0:!1:m;D=a[7];f=void 0!==a[8]?a[8]:f;Y=a[9];Z=a[10];E=void 0!==a[11]?Number(a[11]):E;x.enable=void 0!==a[12]?"true"===a[12]?!0:!1:!1;K=void 0!==a[13]?a[13]:K;h=void 0!==a[14]?a[14]:h}function ta(){if("iFrameResizer"in d&&Object===d.iFrameResizer.constructor){var a=d.iFrameResizer;e("Reading data from page: "+JSON.stringify(a));L="messageCallback"in a?a.messageCallback:L;M="readyCallback"in a?a.readyCallback:
M;y="targetOrigin"in a?a.targetOrigin:y;f="heightCalculationMethod"in a?a.heightCalculationMethod:f;h="widthCalculationMethod"in a?a.widthCalculationMethod:h}e("TargetOrigin for parent set to: "+y)}function ua(a,b){-1!==b.indexOf("-")&&(s("Negative CSS value ignored for "+a),b="");return b}function N(a,b){void 0!==b&&""!==b&&"null"!==b&&(document.body.style[a]=b,e("Body "+a+' set to "'+b+'"'))}function g(a){function b(){n(a.eventName,a.eventType)}var c={add:function(a){B(d,a,b)},remove:function(a){V(d,
a,b)}};if(a.eventNames&&Array.prototype.map)a.eventName=a.eventNames[0],a.eventNames.map(c[a.method]);else c[a.method](a.eventName);e(a.method.charAt(0).toUpperCase()+a.method.slice(1)+" event listener: "+a.eventType)}function $(a){g({method:a,eventType:"Animation Start",eventNames:["animationstart","webkitAnimationStart"]});g({method:a,eventType:"Animation Iteration",eventNames:["animationiteration","webkitAnimationIteration"]});g({method:a,eventType:"Animation End",eventNames:["animationend","webkitAnimationEnd"]});
g({method:a,eventType:"Input",eventName:"input"});g({method:a,eventType:"Mouse Up",eventName:"mouseup"});g({method:a,eventType:"Mouse Down",eventName:"mousedown"});g({method:a,eventType:"Orientation Change",eventName:"orientationchange"});g({method:a,eventType:"Touch Start",eventName:"touchstart"});g({method:a,eventType:"Touch End",eventName:"touchend"});g({method:a,eventType:"Touch Cancel",eventName:"touchcancel"});g({method:a,eventType:"Print",eventName:["afterprint","beforeprint"]});g({method:a,
eventType:"Transition Start",eventNames:["transitionstart","webkitTransitionStart","MSTransitionStart","oTransitionStart","otransitionstart"]});g({method:a,eventType:"Transition Iteration",eventNames:["transitioniteration","webkitTransitionIteration","MSTransitionIteration","oTransitionIteration","otransitioniteration"]});g({method:a,eventType:"Transition End",eventNames:["transitionend","webkitTransitionEnd","MSTransitionEnd","oTransitionEnd","otransitionend"]});"child"===K&&g({method:a,eventType:"IFrame Resized",
eventName:"resize"})}function O(a,b,c,l){b!==a&&(a in c||(s(a+" is not a valid option for "+l+"CalculationMethod."),a=b),e(l+' calculation method set to "'+a+'"'));return a}function aa(){f=O(f,P,p,"height")}function ba(){if(!0===m){$("add");var a=0>r;d.MutationObserver||d.WebKitMutationObserver?a?ca():Q=va():(e("MutationObserver not supported in this browser!"),ca())}else e("Auto Resize disabled")}function da(){$("remove");null!==Q&&Q.disconnect();clearInterval(ea)}function wa(){var a=document.createElement("div");
a.style.clear="both";a.style.display="block";document.body.appendChild(a)}function xa(){function a(a){var b,c;a=a.split("#")[1]||a;b=decodeURIComponent(a);b=document.getElementById(b)||document.getElementsByName(b)[0];if(void 0!==b){c=b.getBoundingClientRect();b=void 0!==d.pageXOffset?d.pageXOffset:document.documentElement.scrollLeft;var g=void 0!==d.pageYOffset?d.pageYOffset:document.documentElement.scrollTop;b=parseInt(c.left,10)+parseInt(b,10);c=parseInt(c.top,10)+parseInt(g,10);e("Moving to in page link (#"+
a+") at x: "+b+" y: "+c);k(c,b,"scrollToOffset")}else e("In page link (#"+a+") not found in iFrame, so sending to parent"),k(0,0,"inPageLink","#"+a)}function b(){""!==location.hash&&"#"!==location.hash&&a(location.href)}function c(){Array.prototype.forEach.call(document.querySelectorAll('a[href^\x3d"#"]'),function(b){function c(b){b.preventDefault();a(this.getAttribute("href"))}"#"!==b.getAttribute("href")&&B(b,"click",c)})}x.enable?Array.prototype.forEach&&document.querySelectorAll?(e("Setting up location.hash handlers"),
c(),B(d,"hashchange",b),setTimeout(b,R)):s("In page linking not fully supported in this browser! (See README.md for IE8 workaround)"):e("In page linking not enabled");return{findTarget:a}}function za(){e("Enable public methods");Aa.parentIFrame={autoResize:function(a){!0===a&&!1===m?(m=!0,ba()):!1===a&&!0===m&&(m=!1,da());return m},close:function(){k(0,0,"close");e("Disable outgoing messages");fa=!1;e("Remove event listener: Message");V(d,"message",ga);da()},getId:function(){return w},getPageInfo:function(a){ha=
a;k(0,0,"pageInfo")},moveToAnchor:function(a){x.findTarget(a)},reset:function(){ia("parentIFrame.reset")},scrollTo:function(a,b){k(b,a,"scrollTo")},scrollToOffset:function(a,b){k(b,a,"scrollToOffset")},sendMessage:function(a,b){k(0,0,"message",JSON.stringify(a),b)},setHeightCalculationMethod:function(a){f=a;aa()},setWidthCalculationMethod:function(a){h=a;h=O(h,S,q,"width")},setTargetOrigin:function(a){e("Set targetOrigin: "+a);y=a},size:function(a,b){n("size","parentIFrame.size("+(""+(a?a:"")+(b?
","+b:""))+")",a,b)}}}function ca(){0!==r&&(e("setInterval: "+r+"ms"),ea=setInterval(function(){n("interval","setInterval: "+r)},Math.abs(r)))}function va(){function a(a){function b(a){!1===a.complete&&(e("Attach listeners to "+a.src),a.addEventListener("load",c,!1),a.addEventListener("error",l,!1),t.push(a))}"attributes"===a.type&&"src"===a.attributeName?b(a.target):"childList"===a.type&&Array.prototype.forEach.call(a.target.querySelectorAll("img"),b)}function b(a){e("Remove listeners from "+a.src);
a.removeEventListener("load",c,!1);a.removeEventListener("error",l,!1);t.splice(t.indexOf(a),1)}function c(a){b(a.target);n("imageLoad","Image loaded: "+a.target.src,void 0,void 0)}function l(a){b(a.target);n("imageLoadFailed","Image load failed: "+a.target.src,void 0,void 0)}function ya(b){n("mutationObserver","mutationObserver: "+b[0].target+" "+b[0].type);b.forEach(a)}var t=[],g=d.MutationObserver||d.WebKitMutationObserver,f=function(){var a=document.querySelector("body");f=new g(ya);e("Create body MutationObserver");
f.observe(a,{attributes:!0,attributeOldValue:!1,characterData:!0,characterDataOldValue:!1,childList:!0,subtree:!0});return f}();return{disconnect:function(){"disconnect"in f&&(e("Disconnect body MutationObserver"),f.disconnect(),t.forEach(b))}}}function T(a){var b=document.body,c=0;if("defaultView"in document&&"getComputedStyle"in document.defaultView)c=document.defaultView.getComputedStyle(b,null),c=null!==c?c[a]:0;else if(a=b.currentStyle[a],/^\d+(px)?$/i.test(a))c=parseInt(a,ja);else{var c=b.style.left,
e=b.runtimeStyle.left;b.runtimeStyle.left=b.currentStyle.left;b.style.left=a||0;a=b.style.pixelLeft;b.style.left=c;b.runtimeStyle.left=e;c=a}return parseInt(c,ja)}function U(a,b){for(var c=b.length,l=0,d=0,t=a.charAt(0).toUpperCase()+a.slice(1),f=F(),g=0;g<c;g++)l=b[g].getBoundingClientRect()[a]+T("margin"+t),l>d&&(d=l);f=F()-f;e("Parsed "+c+" HTML elements");e("Element position calculated in "+f+"ms");f>z/2&&(z=2*f,e("Event throttle increased to "+z+"ms"));return d}function G(a){return[a.bodyOffset(),
a.bodyScroll(),a.documentElementOffset(),a.documentElementScroll()]}function ka(a,b){var c=document.querySelectorAll("["+b+"]");0===c.length?(s("No tagged elements ("+b+") found on page"),c=u):c=U(a,c);return c}function n(a,b,c,d){H&&a in Ba?e("Trigger event cancelled: "+a):(a in{reset:1,resetPage:1,init:1}||e("Trigger event: "+b),Ca(a,b,c,d))}function la(){H||(H=!0,e("Trigger event lock on"));clearTimeout(ma);ma=setTimeout(function(){H=!1;e("Trigger event lock off");e("--")},R)}function na(a){u=
p[f]();A=q[h]();k(u,A,a)}function ia(a){var b=f;f=P;e("Reset trigger event: "+a);la();na("reset");f=b}function k(a,b,c,d,f){!0===fa&&(void 0===f?f=y:e("Message targetOrigin: "+f),a=w+":"+(a+":"+b)+":"+c+(void 0!==d?":"+d:""),e("Sending message to host page ("+a+")"),oa.postMessage(v+a,f))}function ga(a){function b(){W=a.data;oa=a.source;sa();e("Initialising iFrame ("+location.href+")");ta();void 0===D&&(D=J+"px");N("margin",ua("margin",D));N("background",Y);N("padding",Z);wa();aa();h=O(h,S,q,"width");
document.documentElement.style.height="";document.body.style.height="";e('HTML \x26 body height set to "auto"');za();ba();x=xa();n("init","Init message from host page");M();pa=!1;setTimeout(function(){qa=!1},R)}function c(){return a.data.substr(a.data.indexOf(":")+1)}function f(){return a.data.split(":")[2]in{"true":1,"false":1}}function g(){switch(a.data.split("]")[1].split(":")[0]){case "reset":qa?e("Page reset ignored by init"):(e("Page size reset by host page"),na("resetPage"));break;case "resize":n("resizeParent",
"Parent window requested size check");break;case "moveToAnchor":var b=c();x.findTarget(b);break;case "message":b=c();e("MessageCallback called from parent: "+b);L(JSON.parse(b));e(" --");break;case "pageInfo":b=c();e("PageInfoFromParent called from parent: "+b);ha(JSON.parse(b));e(" --");break;default:"iFrameResize"in d||f()||s("Unexpected message ("+a.data+")")}}v===(""+a.data).substr(0,X)&&(!1===pa?g():f()?b():e('Ignored message of type "'+a.data.split("]")[1].split(":")[0]+'". Received before initialization.'))}
var m=!0,ja=10,Y="",J=0,D="",Q=null,Z="",C=!1,Ba={resize:1,click:1},R=128,pa=!0,u=1,P="bodyOffset",f=P,qa=!0,W="",x={},r=32,ea=null,I=!1,v="[iFrameSizer]",X=v.length,w="",ra={max:1,min:1,bodyScroll:1,documentElementScroll:1},K="child",fa=!0,oa=d.parent,y="*",E=0,H=!1,ma=null,z=16,A=1,S="scroll",h=S,Aa=d,L=function(){s("MessageCallback function not defined")},M=function(){},ha=function(){},F=Date.now||function(){return(new Date).getTime()},p={bodyOffset:function(){return document.body.offsetHeight+
T("marginTop")+T("marginBottom")},offset:function(){return p.bodyOffset()},bodyScroll:function(){return document.body.scrollHeight},documentElementOffset:function(){return document.documentElement.offsetHeight},documentElementScroll:function(){return document.documentElement.scrollHeight},max:function(){return Math.max.apply(null,G(p))},min:function(){return Math.min.apply(null,G(p))},grow:function(){return p.max()},lowestElement:function(){return Math.max(p.bodyOffset(),U("bottom",document.querySelectorAll("body *")))},
taggedElement:function(){return ka("bottom","data-iframe-height")}},q={bodyScroll:function(){return document.body.scrollWidth},bodyOffset:function(){return document.body.offsetWidth},documentElementScroll:function(){return document.documentElement.scrollWidth},documentElementOffset:function(){return document.documentElement.offsetWidth},scroll:function(){return Math.max(q.bodyScroll(),q.documentElementScroll())},max:function(){return Math.max.apply(null,G(q))},min:function(){return Math.min.apply(null,
G(q))},rightMostElement:function(){return U("right",document.querySelectorAll("body *"))},taggedElement:function(){return ka("right","data-iframe-width")}},Ca=function(a){var b,c,e,d=null,f=0,g=function(){f=F();d=null;e=a.apply(b,c);d||(b=c=null)};return function(){var h=F();f||(f=h);var k=z-(h-f);b=this;c=arguments;0>=k||k>z?(d&&(clearTimeout(d),d=null),f=h,e=a.apply(b,c),d||(b=c=null)):d||(d=setTimeout(g,k));return e}}(function(a,b,c,d){c=void 0!==c?c:p[f]();d=void 0!==d?d:q[h]();Math.abs(u-c)<=
E&&(!C||Math.abs(A-d)<=E)&&"init"!==a?a in{init:1,interval:1,size:1}||!(f in ra||C&&h in ra)?a in{interval:1}||e("No change in size detected"):ia(b):(la(),u=c,A=d,k(u,A,a))});B(d,"message",ga);"loading"!==document.readyState&&d.parent.postMessage("[iFrameResizerChild]Ready","*")})(window||{});
//# sourceMappingURL=iframeResizer.contentWindow.min.js.map
